cluster.name: ${CLUSTER_NAME} 
node.name: ${HOSTNAME}
node.master: true 
node.data: false
node.ingest: false
network.host: 0.0.0.0 
discovery.zen.ping_timeout: 25s 
processors: 10 
thread_pool.bulk.queue_size: 500
thread_pool.search.queue_size: 500
discovery.zen.ping.unicast.hosts: [ "es-master" ]
